#!/bin/sh

set -e

sudo cp /snap/${SNAPCRAFT_PROJECT_NAME}/current/desktop/mir-kiosk-desktop.desktop /usr/share/wayland-sessions/${SNAPCRAFT_PROJECT_NAME}.desktop
sudo snap connect egmde-confined-desktop:login-session-control

