name: mir-kiosk-desktop
summary: Boilerplate for using mir_kiosk_x11 for a desktop session
description: Boilerplate for using mir_kiosk_x11 for a desktop session (for use as a "stage-snap")
base: core20
confinement: strict
grade: stable
adopt-info: mir-kiosk-desktop

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl pull

  mir-kiosk-desktop:
    after: [ppa-setup]
    plugin: cmake
    source: https://github.com/MirServer/mir_kiosk_x11.git
    override-pull: |
      snapcraftctl pull
      server_version=`git rev-list --count HEAD`
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      snapcraftctl set-version $server_version-mir$mir_version
    build-packages:
      - pkg-config
      - libmiral-dev
      - make
      - g++
    stage-packages:
      - inotify-tools
      - libmiral4
      - mir-graphics-drivers-desktop
      - dmz-cursor-theme
      - fonts-freefont-ttf
      - xwayland
      - libbz2-1.0

  desktop:
    plugin: dump
    source: desktop

  env-setup:
    plugin: dump
    source: env-setup
    override-build: |
      snapcraftctl build
      sed s/\$\{SNAPCRAFT_ARCH_TRIPLET}/${SNAPCRAFT_ARCH_TRIPLET}/g --in-place $SNAPCRAFT_PART_INSTALL/hacks/*
